title: Jiwon Ahn
description: The mechanist blog. Writes primarily about neuroimaging, psychiatry, and ML/DL. Sometimes other quantitative topics such as statistics, physics and economics.
theme: minima